package io.jettra.flux.theme;

/**
 * DarkTheme provides a sleek, modern, and high-contrast dark theme for JettraFlux.
 * Features deep obsidian and slate backgrounds (#090d16 / #0f172a),
 * elevated dark surfaces (#1e293b), elegant indigo-violet primary accents (#6366f1),
 * crystal clear slate-white typography (#f8fafc), and refined glassmorphic accents.
 */
public class DarkTheme {

    public static ThemeData create() {
        return new ThemeData(
            "#6366f1", // primary: Modern Indigo
            "#8b5cf6", // secondary: Violet
            "#090d16", // background: Deep Obsidian Dark
            "#1e293b", // surface: Dark Slate Surface
            "#ffffff", // onPrimary: White text on primary button
            "#f8fafc", // onSurface: High contrast crisp white-slate text
            "border: none; border-radius: 8px; padding: 10px 22px; font-weight: 600; font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #ffffff; background-color: #6366f1; box-shadow: 0 4px 14px rgba(99, 102, 241, 0.35); cursor: pointer; transition: all 0.2s ease;", // buttonStyle
            "border: 1px solid rgba(255, 255, 255, 0.08); border-radius: 12px; padding: 24px; background-color: #1e293b; box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.4), 0 8px 10px -6px rgba(0, 0, 0, 0.4); color: #f8fafc;", // cardStyle
            "padding: 20px; border-radius: 12px; border: 1px solid rgba(255, 255, 255, 0.06); background-color: #162032;", // containerStyle
            "font-size: 15px; color: #f8fafc; font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6;", // textStyle
            Template.CustomCSS,
            Template.CustomJS
        );
    }

    public static class Template {
        public static final String CustomCSS = "<style>\n"
            + "/* DarkTheme Global Enhancements */\n"
            + "@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');\n"
            + "\n"
            + ":root {\n"
            + "  --dark-bg: #090d16;\n"
            + "  --dark-surface: #1e293b;\n"
            + "  --dark-surface-elevated: #26354a;\n"
            + "  --dark-border: rgba(255, 255, 255, 0.09);\n"
            + "  --dark-primary: #6366f1;\n"
            + "  --dark-primary-hover: #4f46e5;\n"
            + "  --dark-text: #f8fafc;\n"
            + "  --dark-text-muted: #94a3b8;\n"
            + "}\n"
            + "\n"
            + "body {\n"
            + "  background-color: var(--dark-bg) !important;\n"
            + "  color: var(--dark-text) !important;\n"
            + "  font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif !important;\n"
            + "  margin: 0;\n"
            + "  padding: 0;\n"
            + "}\n"
            + "\n"
            + "/* Custom Dark Scrollbar */\n"
            + "::-webkit-scrollbar { width: 8px; height: 8px; }\n"
            + "::-webkit-scrollbar-track { background: #090d16; }\n"
            + "::-webkit-scrollbar-thumb { background: #334155; border-radius: 4px; border: 1px solid rgba(255, 255, 255, 0.05); }\n"
            + "::-webkit-scrollbar-thumb:hover { background: #475569; }\n"
            + "\n"
            + "/* Layout Areas */\n"
            + ".espresso-dashboard {\n"
            + "  background-color: var(--dark-bg) !important;\n"
            + "}\n"
            + ".espresso-top, .jettra-topbar {\n"
            + "  background: rgba(15, 23, 42, 0.88) !important;\n"
            + "  backdrop-filter: blur(12px);\n"
            + "  -webkit-backdrop-filter: blur(12px);\n"
            + "  border-bottom: 1px solid var(--dark-border) !important;\n"
            + "  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.3) !important;\n"
            + "  color: var(--dark-text) !important;\n"
            + "  z-index: 10;\n"
            + "}\n"
            + ".espresso-left, .jettra-drawer {\n"
            + "  background: rgba(15, 23, 42, 0.94) !important;\n"
            + "  backdrop-filter: blur(12px);\n"
            + "  -webkit-backdrop-filter: blur(12px);\n"
            + "  border-right: 1px solid var(--dark-border) !important;\n"
            + "  color: var(--dark-text) !important;\n"
            + "  z-index: 5;\n"
            + "}\n"
            + ".espresso-center, .jettra-main-viewport {\n"
            + "  background-color: var(--dark-bg) !important;\n"
            + "  color: var(--dark-text) !important;\n"
            + "}\n"
            + ".espresso-footer {\n"
            + "  background: #0f172a !important;\n"
            + "  border-top: 1px solid var(--dark-border) !important;\n"
            + "  color: var(--dark-text-muted) !important;\n"
            + "  display: flex;\n"
            + "  justify-content: center;\n"
            + "  align-items: center;\n"
            + "}\n"
            + "\n"
            + "/* Sidebar Brand & Category */\n"
            + ".sidebar-logo {\n"
            + "  color: #ffffff !important;\n"
            + "  font-weight: 700;\n"
            + "  letter-spacing: 0.5px;\n"
            + "}\n"
            + ".sidebar-category {\n"
            + "  color: var(--dark-text-muted) !important;\n"
            + "  font-size: 0.75rem;\n"
            + "  font-weight: 700;\n"
            + "  text-transform: uppercase;\n"
            + "  letter-spacing: 0.08em;\n"
            + "}\n"
            + "\n"
            + "/* Sidebar Navigation Links */\n"
            + ".professional-left a, .professional-left p, .espresso-left a, .espresso-left p, .widgetlet-item {\n"
            + "  color: var(--dark-text-muted) !important;\n"
            + "  border-radius: 8px !important;\n"
            + "  padding: 10px 14px !important;\n"
            + "  margin-bottom: 4px;\n"
            + "  transition: all 0.2s ease;\n"
            + "  font-weight: 500;\n"
            + "}\n"
            + ".professional-left a:hover, .professional-left p:hover, .espresso-left a:hover, .espresso-left p:hover, .widgetlet-item:hover {\n"
            + "  background-color: rgba(255, 255, 255, 0.06) !important;\n"
            + "  color: #ffffff !important;\n"
            + "  transform: translateX(3px);\n"
            + "}\n"
            + ".professional-left a.active, .espresso-left a.active {\n"
            + "  background-color: var(--dark-primary) !important;\n"
            + "  color: #ffffff !important;\n"
            + "  font-weight: 600;\n"
            + "  box-shadow: 0 4px 12px rgba(99, 102, 241, 0.35);\n"
            + "}\n"
            + ".professional-left a.active i, .espresso-left a.active i {\n"
            + "  color: #ffffff !important;\n"
            + "}\n"
            + "\n"
            + "/* Buttons */\n"
            + ".espresso-button, .espresso-btn, .btn, .btn-primary {\n"
            + "  background-color: var(--dark-primary) !important;\n"
            + "  color: #ffffff !important;\n"
            + "  border: none !important;\n"
            + "  border-radius: 8px !important;\n"
            + "  padding: 10px 20px !important;\n"
            + "  font-weight: 600 !important;\n"
            + "  box-shadow: 0 4px 14px rgba(99, 102, 241, 0.35) !important;\n"
            + "  cursor: pointer;\n"
            + "  transition: all 0.2s ease;\n"
            + "}\n"
            + ".espresso-button:hover, .espresso-btn:hover, .btn:hover, .btn-primary:hover {\n"
            + "  background-color: var(--dark-primary-hover) !important;\n"
            + "  box-shadow: 0 6px 18px rgba(99, 102, 241, 0.5) !important;\n"
            + "  transform: translateY(-1px);\n"
            + "}\n"
            + ".espresso-btn-outlined, .btn-outline-primary {\n"
            + "  background-color: transparent !important;\n"
            + "  color: var(--dark-primary) !important;\n"
            + "  border: 1px solid var(--dark-primary) !important;\n"
            + "  border-radius: 8px !important;\n"
            + "  padding: 10px 20px !important;\n"
            + "  font-weight: 600 !important;\n"
            + "  transition: all 0.2s ease;\n"
            + "}\n"
            + ".espresso-btn-outlined:hover, .btn-outline-primary:hover {\n"
            + "  background-color: var(--dark-primary) !important;\n"
            + "  color: #ffffff !important;\n"
            + "  transform: translateY(-1px);\n"
            + "}\n"
            + "\n"
            + "/* Cards & Panels */\n"
            + ".espresso-card, .card, .espresso-panel {\n"
            + "  background-color: var(--dark-surface) !important;\n"
            + "  color: var(--dark-text) !important;\n"
            + "  border: 1px solid var(--dark-border) !important;\n"
            + "  border-radius: 12px !important;\n"
            + "  box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.4), 0 8px 10px -6px rgba(0, 0, 0, 0.4) !important;\n"
            + "  padding: 24px;\n"
            + "}\n"
            + ".espresso-panel-header {\n"
            + "  background-color: rgba(15, 23, 42, 0.6) !important;\n"
            + "  color: #ffffff !important;\n"
            + "  border-bottom: 1px solid var(--dark-border) !important;\n"
            + "  font-weight: 600;\n"
            + "  padding: 14px 20px;\n"
            + "}\n"
            + "\n"
            + "/* Form Inputs */\n"
            + ".espresso-textfield, .espresso-textarea, .espresso-select, .espresso-input, .espresso-inputnumber, .form-control, .form-select, input, textarea, select {\n"
            + "  background-color: #0f172a !important;\n"
            + "  color: #f8fafc !important;\n"
            + "  border: 1px solid #334155 !important;\n"
            + "  border-radius: 8px !important;\n"
            + "  padding: 10px 14px;\n"
            + "  font-size: 15px;\n"
            + "  transition: border-color 0.2s, box-shadow 0.2s;\n"
            + "}\n"
            + ".espresso-textfield:focus, .espresso-textarea:focus, .espresso-select:focus, .espresso-input:focus, .form-control:focus, input:focus, textarea:focus, select:focus {\n"
            + "  border-color: var(--dark-primary) !important;\n"
            + "  box-shadow: 0 0 0 3px rgba(99, 102, 241, 0.25) !important;\n"
            + "  outline: none !important;\n"
            + "}\n"
            + "input::placeholder, textarea::placeholder {\n"
            + "  color: #64748b !important;\n"
            + "}\n"
            + "option {\n"
            + "  background-color: #0f172a !important;\n"
            + "  color: #f8fafc !important;\n"
            + "}\n"
            + "\n"
            + "/* Tables & Datatables */\n"
            + ".espresso-datatable, .espresso-table, .table {\n"
            + "  background-color: var(--dark-surface) !important;\n"
            + "  color: var(--dark-text) !important;\n"
            + "  border: 1px solid var(--dark-border) !important;\n"
            + "  border-radius: 10px !important;\n"
            + "  overflow: hidden;\n"
            + "}\n"
            + ".espresso-datatable th, .espresso-table th, .table th {\n"
            + "  background-color: #111827 !important;\n"
            + "  color: var(--dark-text-muted) !important;\n"
            + "  border-bottom: 1px solid var(--dark-border) !important;\n"
            + "  font-weight: 600;\n"
            + "  text-transform: uppercase;\n"
            + "  font-size: 0.8rem;\n"
            + "  letter-spacing: 0.05em;\n"
            + "  padding: 14px 18px;\n"
            + "}\n"
            + ".espresso-datatable td, .espresso-table td, .table td {\n"
            + "  border-bottom: 1px solid rgba(255, 255, 255, 0.05) !important;\n"
            + "  color: var(--dark-text) !important;\n"
            + "  padding: 14px 18px;\n"
            + "}\n"
            + ".espresso-datatable tr:hover td, .espresso-table tr:hover td, .table tr:hover td {\n"
            + "  background-color: rgba(255, 255, 255, 0.04) !important;\n"
            + "}\n"
            + "\n"
            + "/* Badges & Chips */\n"
            + ".espresso-chip, .espresso-badge, .badge, .espresso-tag {\n"
            + "  background-color: rgba(99, 102, 241, 0.18) !important;\n"
            + "  color: #818cf8 !important;\n"
            + "  border: 1px solid rgba(99, 102, 241, 0.35) !important;\n"
            + "  border-radius: 6px !important;\n"
            + "  padding: 4px 10px;\n"
            + "  font-weight: 600;\n"
            + "  font-size: 0.8rem;\n"
            + "}\n"
            + "\n"
            + "/* Modals & Dialogs */\n"
            + ".espresso-modal, .espresso-dialog, .modal-content {\n"
            + "  background-color: #1e293b !important;\n"
            + "  border: 1px solid rgba(255, 255, 255, 0.12) !important;\n"
            + "  border-radius: 16px !important;\n"
            + "  box-shadow: 0 20px 40px rgba(0, 0, 0, 0.6) !important;\n"
            + "  color: #f8fafc !important;\n"
            + "}\n"
            + "\n"
            + "/* Dropdowns & Overlay Menus */\n"
            + ".espresso-overlaymenu, .espresso-dropdown-panel, .dropdown-menu {\n"
            + "  background-color: #1e293b !important;\n"
            + "  border: 1px solid rgba(255, 255, 255, 0.1) !important;\n"
            + "  border-radius: 10px !important;\n"
            + "  box-shadow: 0 10px 25px rgba(0, 0, 0, 0.5) !important;\n"
            + "  color: #f8fafc !important;\n"
            + "}\n"
            + ".espresso-overlaymenu a, .espresso-dropdown-panel a, .dropdown-item {\n"
            + "  color: #cbd5e1 !important;\n"
            + "  padding: 10px 16px;\n"
            + "  border-radius: 6px;\n"
            + "  transition: all 0.15s ease;\n"
            + "}\n"
            + ".espresso-overlaymenu a:hover, .espresso-dropdown-panel a:hover, .dropdown-item:hover {\n"
            + "  background-color: rgba(99, 102, 241, 0.15) !important;\n"
            + "  color: #ffffff !important;\n"
            + "}\n"
            + "</style>";

        public static final String CustomJS = "<script>\n"
            + "function toggleSidebar() {\n"
            + "  var sidebar = document.querySelector('.espresso-left');\n"
            + "  if(sidebar) sidebar.classList.toggle('open');\n"
            + "}\n"
            + "</script>";
    }

    public static class DashboardPage {
        public static final String CustomCSS = "<style>\n"
            + ".darktheme-dashboard-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 1.5rem; width: 100%; }\n"
            + ".darktheme-main-grid { display: grid; grid-template-columns: 2fr 1fr; gap: 1.5rem; width: 100%; margin-top: 1.5rem; }\n"
            + "@media (max-width: 992px) { .darktheme-dashboard-grid, .darktheme-main-grid { grid-template-columns: 1fr; } }\n"
            + ".stat-card { display: flex; flex-direction: column; gap: 10px; background: #1e293b !important; border: 1px solid rgba(255, 255, 255, 0.08) !important; border-radius: 12px !important; box-shadow: 0 10px 25px -5px rgba(0,0,0,0.4) !important; padding: 22px; }\n"
            + ".stat-header { font-size: 0.85rem; color: #94a3b8 !important; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em; }\n"
            + ".stat-value { font-size: 2rem; font-weight: 700; color: #f8fafc !important; }\n"
            + ".stat-badge { padding: 4px 10px; border-radius: 6px; font-size: 0.75rem; font-weight: 600; display: inline-flex; align-items: center; gap: 4px; }\n"
            + ".stat-badge.down { background-color: rgba(239, 68, 68, 0.15) !important; color: #f87171 !important; border: 1px solid rgba(239, 68, 68, 0.3) !important; }\n"
            + ".stat-badge.up { background-color: rgba(34, 197, 94, 0.15) !important; color: #4ade80 !important; border: 1px solid rgba(34, 197, 94, 0.3) !important; }\n"
            + "</style>";
    }
}
