package io.jettra.flux.theme;

/**
 * MatrixTheme provides a cyberpunk/Matrix-inspired visual theme for JettraFlux.
 * Features phosphor neon green accents (#00ff41), deep terminal blacks, glowing borders,
 * monospace typography, and an optional subtle animated digital rain background canvas.
 */
public class MatrixTheme {

    public static ThemeData create() {
        return new ThemeData(
            "#00ff41", // primary: Matrix Neon Green
            "#008f11", // secondary: Matrix Dark Digital Green
            "#020b02", // background: Deep Matrix Abyss Black
            "#061406", // surface: Dark Matrix Terminal Surface
            "#000000", // onPrimary: High contrast black text on neon green
            "#00ff66", // onSurface: Phosphor green text
            "border: 1px solid #00ff41; border-radius: 4px; padding: 10px 20px; font-weight: bold; font-family: 'JetBrains Mono', 'Courier New', monospace; color: #000000; background-color: #00ff41; box-shadow: 0 0 12px rgba(0, 255, 65, 0.4); cursor: pointer; text-transform: uppercase; transition: all 0.2s ease;", // buttonStyle
            "border: 1px solid rgba(0, 255, 65, 0.35); border-radius: 6px; padding: 20px; background-color: rgba(6, 20, 6, 0.9); box-shadow: 0 0 15px rgba(0, 255, 65, 0.15), inset 0 0 15px rgba(0, 255, 65, 0.05); color: #00ff66;", // cardStyle
            "padding: 16px; border-radius: 4px; border: 1px solid rgba(0, 255, 65, 0.2); background-color: rgba(2, 11, 2, 0.85);", // containerStyle
            "font-size: 15px; color: #00ff66; font-family: 'JetBrains Mono', 'Courier New', monospace; text-shadow: 0 0 4px rgba(0, 255, 65, 0.4);", // textStyle
            Template.CustomCSS,
            Template.CustomJS
        );
    }

    public static class Template {
        public static final String CustomCSS = "<style>\n"
            + "/* Matrix Theme Global Component Enhancements */\n"
            + "* {\n"
            + "  font-family: 'JetBrains Mono', 'Fira Code', 'Courier New', monospace !important;\n"
            + "}\n"
            + "body {\n"
            + "  background-color: #020b02 !important;\n"
            + "  color: #00ff66 !important;\n"
            + "  text-shadow: 0 0 2px rgba(0, 255, 65, 0.3);\n"
            + "}\n"
            + "/* Matrix Scrollbar */\n"
            + "::-webkit-scrollbar { width: 8px; height: 8px; }\n"
            + "::-webkit-scrollbar-track { background: #020b02; }\n"
            + "::-webkit-scrollbar-thumb { background: #005500; border-radius: 4px; border: 1px solid #00ff41; }\n"
            + "::-webkit-scrollbar-thumb:hover { background: #00ff41; box-shadow: 0 0 10px #00ff41; }\n"
            + "\n"
            + "/* Layout Areas */\n"
            + ".espresso-dashboard { background-color: #020b02 !important; }\n"
            + ".espresso-top, .jettra-topbar { background-color: rgba(6, 20, 6, 0.95) !important; border-bottom: 1px solid #00ff41 !important; box-shadow: 0 2px 15px rgba(0, 255, 65, 0.15) !important; color: #00ff41 !important; }\n"
            + ".espresso-left, .jettra-drawer { background-color: rgba(4, 15, 4, 0.95) !important; border-right: 1px solid rgba(0, 255, 65, 0.3) !important; color: #00ff66 !important; }\n"
            + ".espresso-center, .jettra-main-viewport { background-color: transparent !important; color: #00ff66 !important; }\n"
            + ".espresso-footer { background-color: rgba(6, 20, 6, 0.95) !important; border-top: 1px solid rgba(0, 255, 65, 0.2) !important; color: #008f11 !important; }\n"
            + "\n"
            + "/* Navigation Links & Active States */\n"
            + ".professional-left a, .professional-left p, .espresso-left a, .espresso-left p, .widgetlet-item {\n"
            + "  color: #00ff66 !important; transition: all 0.2s ease;\n"
            + "}\n"
            + ".professional-left a:hover, .professional-left p:hover, .espresso-left a:hover, .espresso-left p:hover, .widgetlet-item:hover {\n"
            + "  background-color: rgba(0, 255, 65, 0.15) !important; color: #00ff41 !important; text-shadow: 0 0 8px #00ff41; padding-left: 18px !important;\n"
            + "}\n"
            + ".professional-left a.active, .espresso-left a.active {\n"
            + "  background-color: rgba(0, 255, 65, 0.25) !important; color: #00ff41 !important; border-left: 3px solid #00ff41 !important; box-shadow: 0 0 10px rgba(0, 255, 65, 0.2);\n"
            + "}\n"
            + ".professional-left i, .espresso-left i, .top-right-section i, .jettra-hamburger {\n"
            + "  color: #00ff41 !important; text-shadow: 0 0 6px rgba(0, 255, 65, 0.6);\n"
            + "}\n"
            + "\n"
            + "/* Buttons */\n"
            + ".espresso-button, .espresso-btn, .btn, .btn-primary {\n"
            + "  background-color: #00ff41 !important;\n"
            + "  color: #000000 !important;\n"
            + "  border: 1px solid #00ff41 !important;\n"
            + "  box-shadow: 0 0 10px rgba(0, 255, 65, 0.35) !important;\n"
            + "  font-weight: 700 !important;\n"
            + "  text-transform: uppercase;\n"
            + "  letter-spacing: 1px;\n"
            + "  transition: all 0.2s ease-in-out;\n"
            + "}\n"
            + ".espresso-button:hover, .espresso-btn:hover, .btn:hover, .btn-primary:hover {\n"
            + "  background-color: #39ff14 !important;\n"
            + "  box-shadow: 0 0 20px rgba(0, 255, 65, 0.8) !important;\n"
            + "  transform: translateY(-1px);\n"
            + "}\n"
            + ".espresso-btn-outlined, .btn-outline-primary {\n"
            + "  background-color: transparent !important;\n"
            + "  color: #00ff41 !important;\n"
            + "  border: 1px solid #00ff41 !important;\n"
            + "}\n"
            + ".espresso-btn-outlined:hover, .btn-outline-primary:hover {\n"
            + "  background-color: #00ff41 !important;\n"
            + "  color: #000000 !important;\n"
            + "  box-shadow: 0 0 15px #00ff41 !important;\n"
            + "}\n"
            + "\n"
            + "/* Cards & Panels */\n"
            + ".espresso-card, .card, .espresso-panel {\n"
            + "  background-color: rgba(6, 20, 6, 0.9) !important;\n"
            + "  color: #00ff66 !important;\n"
            + "  border: 1px solid rgba(0, 255, 65, 0.35) !important;\n"
            + "  box-shadow: 0 0 15px rgba(0, 255, 65, 0.15), inset 0 0 15px rgba(0, 255, 65, 0.05) !important;\n"
            + "  backdrop-filter: blur(8px);\n"
            + "}\n"
            + ".espresso-panel-header {\n"
            + "  background-color: rgba(2, 11, 2, 0.9) !important;\n"
            + "  color: #00ff41 !important;\n"
            + "  border-bottom: 1px solid rgba(0, 255, 65, 0.3) !important;\n"
            + "  text-transform: uppercase;\n"
            + "  letter-spacing: 1px;\n"
            + "}\n"
            + "\n"
            + "/* Form Inputs */\n"
            + ".espresso-textfield, .espresso-textarea, .espresso-select, .espresso-input, .espresso-inputnumber, .form-control, .form-select, input, textarea, select {\n"
            + "  background-color: rgba(2, 14, 2, 0.9) !important;\n"
            + "  color: #00ff41 !important;\n"
            + "  border: 1px solid rgba(0, 255, 65, 0.4) !important;\n"
            + "  caret-color: #00ff41 !important;\n"
            + "  text-shadow: 0 0 3px rgba(0, 255, 65, 0.4);\n"
            + "}\n"
            + ".espresso-textfield:focus, .espresso-textarea:focus, .espresso-select:focus, .espresso-input:focus, .form-control:focus, input:focus, textarea:focus, select:focus {\n"
            + "  border-color: #00ff41 !important;\n"
            + "  box-shadow: 0 0 12px rgba(0, 255, 65, 0.6) !important;\n"
            + "  outline: none !important;\n"
            + "}\n"
            + "input::placeholder, textarea::placeholder {\n"
            + "  color: rgba(0, 255, 65, 0.4) !important;\n"
            + "}\n"
            + "option {\n"
            + "  background-color: #020b02 !important;\n"
            + "  color: #00ff41 !important;\n"
            + "}\n"
            + "\n"
            + "/* Tables */\n"
            + ".espresso-datatable, .espresso-table, .table {\n"
            + "  background-color: rgba(4, 16, 4, 0.85) !important;\n"
            + "  color: #00ff66 !important;\n"
            + "  border: 1px solid rgba(0, 255, 65, 0.3) !important;\n"
            + "}\n"
            + ".espresso-datatable th, .espresso-table th, .table th {\n"
            + "  background-color: rgba(0, 30, 0, 0.95) !important;\n"
            + "  color: #00ff41 !important;\n"
            + "  border-bottom: 2px solid #00ff41 !important;\n"
            + "  border-top: 1px solid rgba(0, 255, 65, 0.2) !important;\n"
            + "  text-transform: uppercase;\n"
            + "  letter-spacing: 1px;\n"
            + "}\n"
            + ".espresso-datatable td, .espresso-table td, .table td {\n"
            + "  border-bottom: 1px solid rgba(0, 255, 65, 0.15) !important;\n"
            + "  color: #00ff66 !important;\n"
            + "}\n"
            + ".espresso-datatable tr:hover td, .espresso-table tr:hover td, .table tr:hover td {\n"
            + "  background-color: rgba(0, 255, 65, 0.12) !important;\n"
            + "  color: #ffffff !important;\n"
            + "  text-shadow: 0 0 6px #00ff41;\n"
            + "}\n"
            + "\n"
            + "/* Modals & Dialogs */\n"
            + ".espresso-modal, .espresso-dialog, .modal-content {\n"
            + "  background-color: rgba(4, 18, 4, 0.95) !important;\n"
            + "  border: 2px solid #00ff41 !important;\n"
            + "  box-shadow: 0 0 30px rgba(0, 255, 65, 0.4) !important;\n"
            + "  color: #00ff66 !important;\n"
            + "}\n"
            + "\n"
            + "/* Tabs & Accordions */\n"
            + ".espresso-tabview-nav-link { color: #008f11 !important; }\n"
            + ".espresso-tabview-nav-link:hover { color: #00ff41 !important; }\n"
            + ".espresso-tabview-nav-active .espresso-tabview-nav-link { color: #00ff41 !important; border-bottom: 2px solid #00ff41 !important; text-shadow: 0 0 8px #00ff41; }\n"
            + ".espresso-accordion-tab { border-color: rgba(0, 255, 65, 0.3) !important; }\n"
            + ".espresso-accordion-header { background-color: rgba(2, 12, 2, 0.9) !important; color: #00ff41 !important; }\n"
            + ".espresso-accordion-header:hover { background-color: rgba(0, 255, 65, 0.15) !important; }\n"
            + "\n"
            + "/* Badges, Chips & Tags */\n"
            + ".espresso-chip, .espresso-badge, .badge, .espresso-tag {\n"
            + "  background-color: rgba(0, 255, 65, 0.15) !important;\n"
            + "  color: #00ff41 !important;\n"
            + "  border: 1px solid #00ff41 !important;\n"
            + "  box-shadow: 0 0 6px rgba(0, 255, 65, 0.3) !important;\n"
            + "}\n"
            + "\n"
            + "/* Dropdowns & Overlay Menus */\n"
            + ".espresso-overlaymenu, .espresso-dropdown-panel, .dropdown-menu {\n"
            + "  background-color: rgba(4, 18, 4, 0.95) !important;\n"
            + "  border: 1px solid #00ff41 !important;\n"
            + "  box-shadow: 0 0 20px rgba(0, 255, 65, 0.3) !important;\n"
            + "  color: #00ff66 !important;\n"
            + "}\n"
            + ".espresso-overlaymenu a, .espresso-dropdown-panel a, .dropdown-item {\n"
            + "  color: #00ff66 !important;\n"
            + "}\n"
            + ".espresso-overlaymenu a:hover, .espresso-dropdown-panel a:hover, .dropdown-item:hover {\n"
            + "  background-color: rgba(0, 255, 65, 0.2) !important;\n"
            + "  color: #00ff41 !important;\n"
            + "  text-shadow: 0 0 8px #00ff41;\n"
            + "}\n"
            + "</style>";

        public static final String CustomJS = "<script>\n"
            + "(function() {\n"
            + "  function initMatrixRain() {\n"
            + "    if (document.getElementById('matrix-rain-canvas')) return;\n"
            + "    var canvas = document.createElement('canvas');\n"
            + "    canvas.id = 'matrix-rain-canvas';\n"
            + "    canvas.style.position = 'fixed';\n"
            + "    canvas.style.top = '0';\n"
            + "    canvas.style.left = '0';\n"
            + "    canvas.style.width = '100vw';\n"
            + "    canvas.style.height = '100vh';\n"
            + "    canvas.style.zIndex = '0';\n"
            + "    canvas.style.pointerEvents = 'none';\n"
            + "    canvas.style.opacity = '0.16';\n"
            + "    document.body.prepend(canvas);\n"
            + "\n"
            + "    var ctx = canvas.getContext('2d');\n"
            + "    var w, h, cols, ypos;\n"
            + "\n"
            + "    function resize() {\n"
            + "      w = canvas.width = window.innerWidth;\n"
            + "      h = canvas.height = window.innerHeight;\n"
            + "      cols = Math.floor(w / 20) + 1;\n"
            + "      ypos = Array(cols).fill(0).map(function() { return Math.floor(Math.random() * 50); });\n"
            + "    }\n"
            + "    resize();\n"
            + "    window.addEventListener('resize', resize);\n"
            + "\n"
            + "    var chars = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZｦｱｳｴｵｶｷｹｺｻｼｽｾｿﾀﾂﾃﾅﾆﾇﾈﾊﾋﾎﾏﾐﾑﾒﾓﾔﾕﾗﾘﾜ';\n"
            + "    var lastTime = 0;\n"
            + "\n"
            + "    function matrixStep(time) {\n"
            + "      requestAnimationFrame(matrixStep);\n"
            + "      if (time - lastTime < 33) return; // ~30 fps cap\n"
            + "      lastTime = time;\n"
            + "\n"
            + "      ctx.fillStyle = 'rgba(2, 11, 2, 0.08)';\n"
            + "      ctx.fillRect(0, 0, w, h);\n"
            + "      ctx.fillStyle = '#00ff41';\n"
            + "      ctx.font = '14px monospace';\n"
            + "\n"
            + "      for (var i = 0; i < cols; i++) {\n"
            + "        var text = chars.charAt(Math.floor(Math.random() * chars.length));\n"
            + "        var x = i * 20;\n"
            + "        var y = ypos[i] * 20;\n"
            + "        ctx.fillText(text, x, y);\n"
            + "        if (y > 100 + Math.random() * 10000) ypos[i] = 0;\n"
            + "        else ypos[i]++;\n"
            + "      }\n"
            + "    }\n"
            + "    requestAnimationFrame(matrixStep);\n"
            + "  }\n"
            + "  if (document.readyState === 'loading') {\n"
            + "    document.addEventListener('DOMContentLoaded', initMatrixRain);\n"
            + "  } else {\n"
            + "    initMatrixRain();\n"
            + "  }\n"
            + "})();\n"
            + "</script>";
    }

    public static class DashboardPage {
        public static final String CustomCSS = "<style>\n"
            + ".matrix-dashboard-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 1.5rem; width: 100%; }\n"
            + ".matrix-main-grid { display: grid; grid-template-columns: 2fr 1fr; gap: 1.5rem; width: 100%; margin-top: 1.5rem; }\n"
            + "@media (max-width: 992px) { .matrix-dashboard-grid, .matrix-main-grid { grid-template-columns: 1fr; } }\n"
            + ".stat-card { display: flex; flex-direction: column; gap: 10px; background: rgba(6, 20, 6, 0.9) !important; border: 1px solid #00ff41 !important; box-shadow: 0 0 15px rgba(0, 255, 65, 0.2) !important; }\n"
            + ".stat-header { font-size: 0.85rem; color: #008f11 !important; font-weight: 700; text-transform: uppercase; letter-spacing: 1px; }\n"
            + ".stat-value { font-size: 2rem; font-weight: 700; color: #00ff41 !important; text-shadow: 0 0 10px #00ff41; }\n"
            + ".stat-badge { padding: 4px 8px; border-radius: 4px; font-size: 0.75rem; font-weight: bold; display: inline-flex; align-items: center; gap: 4px; border: 1px solid currentColor; }\n"
            + ".stat-badge.down { background-color: rgba(239, 68, 68, 0.2) !important; color: #ff5555 !important; }\n"
            + ".stat-badge.up { background-color: rgba(0, 255, 65, 0.2) !important; color: #00ff41 !important; }\n"
            + "</style>";
    }
}
